@host = https://localhost
@port = 7192
@KanjiLearn.Server_HostAddress = {{host}}:{{port}}

GET {{KanjiLearn.Server_HostAddress}}/api/kanji
Accept: application/json
Accept-Charset: utf-16

### Get all Kanji

GET {{KanjiLearn.Server_HostAddress}}/api/kanji/1
Accept: application/json
Accept-Charset: utf-16

### Get Kanji with id 1

GET {{KanjiLearn.Server_HostAddress}}/api/kanji/999999
Accept: application/json
Accept-Charset: utf-16

### Kanji of id 999999 not found. The status should be 404

POST {{KanjiLearn.Server_HostAddress}}/api/kanji
Accept: text/plain
Content-Type: application/json

{
  "character": "T",
  "translation": "translationTest",
  "strokes": 50,
  "kunyomi": " kunyomiTest",
  "onyomi": "onyomiTest",
  "created": "2024-04-11T11:11:11.1111Z",
  "lastModified": "2024-04-11T11:11:11.1111Z"
}

### Create new Kanji with readings

DELETE {{KanjiLearn.Server_HostAddress}}/api/kanji/8

### Delete Kanji