// <auto-generated />
using System;
using KanjiLearn.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KanjiLearn.Server.Migrations
{
    [DbContext(typeof(KanjiLearnContext))]
    partial class KanjiLearnContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KanjiLearn.Server.Models.Kanji", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Character")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Strokes")
                        .HasMaxLength(2)
                        .HasColumnType("integer");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("Kanji");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Character = "人",
                            Created = new DateTime(2023, 12, 11, 15, 37, 39, 880, DateTimeKind.Utc).AddTicks(8633),
                            LastModified = new DateTime(2023, 12, 11, 15, 37, 39, 880, DateTimeKind.Utc).AddTicks(8636),
                            Strokes = 2,
                            Translation = "Człowiek"
                        },
                        new
                        {
                            Id = 2,
                            Character = "日",
                            Created = new DateTime(2023, 12, 11, 15, 37, 39, 880, DateTimeKind.Utc).AddTicks(8638),
                            LastModified = new DateTime(2023, 12, 11, 15, 37, 39, 880, DateTimeKind.Utc).AddTicks(8639),
                            Strokes = 4,
                            Translation = "Dzień, słońce"
                        });
                });

            modelBuilder.Entity("KanjiLearn.Server.Models.Readings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("KanjiId")
                        .HasColumnType("integer");

                    b.Property<string>("Kunyomi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Onyomi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("KanjiId");

                    b.ToTable("Readings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2023, 12, 11, 15, 37, 39, 880, DateTimeKind.Utc).AddTicks(8997),
                            KanjiId = 1,
                            Kunyomi = "ジン、ニン",
                            LastModified = new DateTime(2023, 12, 11, 15, 37, 39, 880, DateTimeKind.Utc).AddTicks(8998),
                            Onyomi = "ひと"
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2023, 12, 11, 15, 37, 39, 880, DateTimeKind.Utc).AddTicks(9000),
                            KanjiId = 2,
                            Kunyomi = "ニチ、 ジツ",
                            LastModified = new DateTime(2023, 12, 11, 15, 37, 39, 880, DateTimeKind.Utc).AddTicks(9000),
                            Onyomi = "ひ、び"
                        });
                });

            modelBuilder.Entity("KanjiLearn.Server.Models.Sentences", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("KanjiId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReadingKanjiInSentence")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Sentence")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("SentenceKanji")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("TranslationReadingKanjiInSentence")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("KanjiId");

                    b.ToTable("Sentences");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2023, 12, 11, 15, 37, 39, 880, DateTimeKind.Utc).AddTicks(9029),
                            KanjiId = 1,
                            LastModified = new DateTime(2023, 12, 11, 15, 37, 39, 880, DateTimeKind.Utc).AddTicks(9030),
                            ReadingKanjiInSentence = "ひと",
                            Sentence = "この人はにほんじんです。",
                            SentenceKanji = "人",
                            Translation = "Ten człowiek jest Japończykiem.",
                            TranslationReadingKanjiInSentence = "człowiek"
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2023, 12, 11, 15, 37, 39, 880, DateTimeKind.Utc).AddTicks(9037),
                            KanjiId = 1,
                            LastModified = new DateTime(2023, 12, 11, 15, 37, 39, 880, DateTimeKind.Utc).AddTicks(9038),
                            ReadingKanjiInSentence = "ひとびと",
                            Sentence = "なぜ人々はほんをよみますか。",
                            SentenceKanji = "人々",
                            Translation = "Dlaczego ludzie czytają książki?",
                            TranslationReadingKanjiInSentence = "ludzie"
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2023, 12, 11, 15, 37, 39, 880, DateTimeKind.Utc).AddTicks(9041),
                            KanjiId = 2,
                            LastModified = new DateTime(2023, 12, 11, 15, 37, 39, 880, DateTimeKind.Utc).AddTicks(9042),
                            ReadingKanjiInSentence = "ひ",
                            Sentence = "ほんとうにいい日でした",
                            SentenceKanji = "日",
                            Translation = "Ten dzień był naprawdę dobry.",
                            TranslationReadingKanjiInSentence = "dzień"
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTime(2023, 12, 11, 15, 37, 39, 880, DateTimeKind.Utc).AddTicks(9046),
                            KanjiId = 2,
                            LastModified = new DateTime(2023, 12, 11, 15, 37, 39, 880, DateTimeKind.Utc).AddTicks(9047),
                            ReadingKanjiInSentence = "ひび",
                            Sentence = "ともだちとあうとき、むかしの日々をおもいだします。",
                            SentenceKanji = "日々",
                            Translation = "Gdy spotykam się z przyjacielem, przypominają mi się dawne czasy.",
                            TranslationReadingKanjiInSentence = "codziennie, dni"
                        });
                });

            modelBuilder.Entity("KanjiLearn.Server.Models.Readings", b =>
                {
                    b.HasOne("KanjiLearn.Server.Models.Kanji", null)
                        .WithOne("Readings")
                        .HasForeignKey("KanjiLearn.Server.Models.Readings", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KanjiLearn.Server.Models.Kanji", "Kanji")
                        .WithMany()
                        .HasForeignKey("KanjiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kanji");
                });

            modelBuilder.Entity("KanjiLearn.Server.Models.Sentences", b =>
                {
                    b.HasOne("KanjiLearn.Server.Models.Kanji", "Kanji")
                        .WithMany("Sentences")
                        .HasForeignKey("KanjiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kanji");
                });

            modelBuilder.Entity("KanjiLearn.Server.Models.Kanji", b =>
                {
                    b.Navigation("Readings")
                        .IsRequired();

                    b.Navigation("Sentences");
                });
#pragma warning restore 612, 618
        }
    }
}
